# Generated by Django 6.0.4 on 2026-04-08 07:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clinic',
            fields=[
                ('clinic_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('clinic_name', models.CharField(max_length=255)),
                ('address_line', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('pincode', models.CharField(max_length=10)),
                ('contact_number', models.CharField(max_length=20)),
                ('clinic_type', models.CharField(max_length=100)),
                ('bed_capacity', models.IntegerField(default=0)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('established_year', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Disease',
            fields=[
                ('disease_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('icd_10_code', models.CharField(max_length=20)),
                ('disease_name', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=100)),
                ('seasonality_flag', models.CharField(choices=[('Monsoon', 'Monsoon'), ('Summer', 'Summer'), ('Winter', 'Winter'), ('All-Year', 'All-Year')], max_length=20)),
                ('severity_level', models.CharField(max_length=20)),
                ('avg_recovery_days', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('patient_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('dob', models.DateField()),
                ('gender', models.CharField(max_length=10)),
                ('blood_group', models.CharField(max_length=5)),
                ('city', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('pincode', models.CharField(max_length=10)),
                ('occupation_type', models.CharField(max_length=100)),
                ('chronic_conditions_flag', models.BooleanField(default=False)),
                ('registration_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('appointment_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('appointment_date', models.DateField()),
                ('vitals_temperature', models.DecimalField(decimal_places=2, max_digits=5)),
                ('status', models.CharField(max_length=50)),
                ('visit_type', models.CharField(max_length=50)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinical.clinic')),
                ('disease', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clinical.disease')),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('doctor_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('specialization', models.CharField(max_length=100)),
                ('experience_years', models.IntegerField()),
                ('consultation_fee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('average_rating', models.DecimalField(decimal_places=1, max_digits=3)),
                ('availability_status', models.CharField(default='Active', max_length=20)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinical.clinic')),
            ],
        ),
    ]
