# Generated by Django 6.0.4 on 2026-04-08 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyticsAlert',
            fields=[
                ('alert_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('alert_type', models.CharField(max_length=100)),
                ('reference_id', models.CharField(max_length=20)),
                ('severity', models.CharField(max_length=20)),
                ('trigger_metric', models.TextField()),
                ('triggered_date', models.DateField()),
                ('is_resolved', models.BooleanField(default=False)),
            ],
        ),
    ]
