# Generated by Django 6.0.4 on 2026-04-08 07:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('analytics', '0001_initial'),
        ('clinical', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='analyticsalert',
            name='clinic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinical.clinic'),
        ),
    ]
