# Generated by Django 6.0.4 on 2026-04-08 07:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clinical', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DrugMaster',
            fields=[
                ('drug_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('generic_name', models.CharField(max_length=255)),
                ('brand_name', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=100)),
                ('current_stock_level', models.IntegerField()),
                ('minimum_safety_buffer', models.IntegerField()),
                ('unit_cost_inr', models.DecimalField(decimal_places=2, max_digits=10)),
                ('lead_time_days', models.IntegerField()),
                ('requires_prescription', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('prescription_id', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('date_issued', models.DateField()),
                ('duration_days', models.IntegerField()),
                ('digital_signature_flag', models.BooleanField(default=True)),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinical.appointment')),
            ],
        ),
        migrations.CreateModel(
            name='PrescriptionLine',
            fields=[
                ('line_id', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('dosage_frequency', models.CharField(max_length=20)),
                ('quantity_dispensed', models.IntegerField()),
                ('drug', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pharmacy.drugmaster')),
                ('prescription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='pharmacy.prescription')),
            ],
        ),
    ]
