# Generated by Django 6.0.4 on 2026-04-09 07:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DrugBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_number', models.CharField(max_length=50, unique=True)),
                ('expiry_date', models.DateField()),
                ('quantity_received', models.IntegerField()),
                ('current_quantity', models.IntegerField()),
                ('procurement_date', models.DateField(auto_now_add=True)),
                ('drug', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='pharmacy.drugmaster')),
            ],
        ),
    ]
